# Generated by Django 5.0.2 on 2024-04-30 10:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('depart_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='leave_type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'permissions': [('can_add_types_assign', 'can add type assign')],
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LeaveApp.department')),
                ('user_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='leaveRequest',
            fields=[
                ('leaveRequest_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_applied', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('comments', models.CharField(blank=True, max_length=250, null=True)),
                ('no_of_days', models.IntegerField()),
                ('resumption_date', models.DateField(default='2024-08-04')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('sub_comments', models.CharField(blank=True, max_length=250, null=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeaveApp.employee')),
                ('leave_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LeaveApp.leave_type')),
            ],
            options={
                'permissions': [('can_see_approved_leave', 'can see approved leave'), ('can_see_submitted_leave', 'can see submitted leave')],
            },
        ),
        migrations.CreateModel(
            name='subtitute',
            fields=[
                ('subtitute_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(blank=True, max_length=250, null=True)),
                ('leaveRequest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeaveApp.leaverequest')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeaveApp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('supervisor_id', models.AutoField(primary_key=True, serialize=False)),
                ('subordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subordinates', to='LeaveApp.employee')),
                ('supervisor_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to='LeaveApp.employee')),
            ],
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LeaveApp.supervisor'),
        ),
        migrations.CreateModel(
            name='unit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeaveApp.department')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LeaveApp.unit'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Admin'), (2, 'Supervisor'), (3, 'Staff'), (4, 'Super Admin')])),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LeaveApp.userrole'),
        ),
        migrations.AddConstraint(
            model_name='supervisor',
            constraint=models.UniqueConstraint(fields=('supervisor_employee', 'subordinate'), name='unique_supervisor_subordinate'),
        ),
    ]
