# Generated by Django 5.0.2 on 2024-04-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('can_add_new_employee', 'can add new employee')]},
        ),
    ]
