# Generated by Django 5.0.2 on 2024-02-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='emp',
        ),
        migrations.AddField(
            model_name='leave',
            name='email',
            field=models.EmailField(blank=True, default='frontdesk@gmail.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='approved',
            field=models.BooleanField(blank=True, default=False, verbose_name='Approved'),
        ),
    ]
