# Generated by Django 5.0.2 on 2024-03-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0004_remove_leave_type_other_type_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='sub_comments',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='leave',
        ),
    ]
