# Generated by Django 5.0.2 on 2024-03-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0005_leaverequest_sub_comments_delete_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_type',
            name='other_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
