# Generated by Django 5.0.2 on 2024-03-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0006_leave_type_other_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='leave_type',
            name='other_name',
        ),
    ]
