# Generated by Django 5.0.2 on 2024-03-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0007_remove_employee_email_remove_leave_type_other_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='Phis3@gmail.com', max_length=254),
        ),
    ]
