# Generated by Django 5.0.2 on 2024-03-05 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0008_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='resumption_date',
            field=models.DateField(default='2024-08-04'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LeaveApp.leave_type'),
        ),
    ]
