# Generated by Django 5.0.2 on 2024-03-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0010_alter_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
