# Generated by Django 5.0.2 on 2024-03-19 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0011_remove_employee_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('can_add_new_employee', 'can add new employee')]},
        ),
    ]
