# Generated by Django 5.0.2 on 2024-03-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0013_alter_leaverequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave_type',
            options={'permissions': [('can_add_types_assign', 'can add type assign')]},
        ),
    ]
